#!/bin/bash

set -e

LOCATION="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
DIRECTORY=$($LOCATION/tasks-home)/$($LOCATION/tasks-which)
mkdir -p $DIRECTORY

usage() {
    cat <<TXT
USAGE: tasks edit <id> [message]

ALIASES:
    e

ARGUMENTS:
    id       The task id
    message  The message to replace the task with
TXT
}

#
# Edit a log item
#
# TODO: It still needs to be done
#
edit() {
    echo "TODO"
}

edit $*
