#!/bin/bash

set -e

LOCATION="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
DIRECTORY=$($LOCATION/tasks-home)/current
mkdir -p $DIRECTORY

if [[ ! -f $DIRECTORY/current.log ]]
then
    touch $DIRECTORY/current.log
fi

NOW=$(date +"%F %R")

usage() {
    cat <<TXT
USAGE: task remove <id>

ALIASES:
    rm

ARGUMENTS:
    id  The task id
TXT
}

#
# Remove an item from the log
#
remove() {
    if [[ -z $1 ]]
    then
        usage
        exit 1
    fi

    local id=$1
    local original=$(rg -m 1 -e "$id - \\[.\\] - .*" $DIRECTORY/current.log)

    echo "$original" >> $DIRECTORY/deleted.log
    sed -i "/\($id - \\[.\\] - .*\)/d" $DIRECTORY/current.log
    echo "Removed $id"
}

remove $*
