#!/bin/bash

set -e

DIRECTORY=$(tasks-home)/$(tasks-which)

usage() {
    cat <<TXT
USAGE: tasks edit <id> [message]

ALIASES:
    e

ARGUMENTS:
    id       The task id
    message  The message to replace the task with
TXT
}

#
# Edit a log item
#
# TODO: It still needs to be done
#
edit() {
    echo "TODO"
}

edit $*
