#!/bin/bash

set -e

LOCATION="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
DIRECTORY=$($LOCATION/tasks-home)
mkdir -p $DIRECTORY

if [[ ! -f $DIRECTORY/org ]]
then
    echo "default" > $DIRECTORY/org
fi

cat $DIRECTORY/org
