#!/bin/bash

set -e

LOCATION="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
DIRECTORY=$($LOCATION/tasks-home)/current

# Check to ensure our counter is still present
if [[ ! -f $DIRECTORY/taskid ]]
then
    echo "0" > $DIRECTORY/taskid
fi

# Check to make sure the log files are present
if [[ ! -f $DIRECTORY/current.log ]]
then
    touch $DIRECTORY/current.log
fi

if [[ ! -f $DIRECTORY/archived.log ]]
then
    touch $DIRECTORY/archived.log
fi

if [[ ! -f $DIRECTORY/deleted.log ]]
then
    touch $DIRECTORY/deleted.log
fi
