#!/bin/bash

set -e

DIRECTORY=$(tasks-home)/$(tasks-which)

if [[ ! -f $DIRECTORY/current.log ]]
then
    touch $DIRECTORY/current.log
fi

NOW=$(date +"%F %R")

remove_completed_tag() {
    perl -pe 's/\@completed\(.*\)//g'
}

trim_trailing() {
    perl -pe 's/\s+$//g'
}

usage() {
    cat <<TXT
USAGE: task uncomplete <id>

ALIASES:
    C

ARGUMENTS:
    id  The task id
TXT
}

#
# Mark a task as incomplete
#
uncomplete() {
    if [[ -z $1 ]]
    then
        usage
        exit 1
    fi

    ID=$1

    original=$(rg -m 1 -e "$ID - \\[x\\] - (.*)" --replace '$1' $DIRECTORY/current.log)

    sed -i "/\($ID - \\[x\\] - .*\)/d" $DIRECTORY/current.log

    original=$(echo $original | remove_completed_tag | trim_trailing)
    message="$ID - [ ] - $original"
    echo $message >> $DIRECTORY/current.log
    echo $message
}

uncomplete $*
