#!/bin/bash

set -e

TASKS_DIRECTORY="${TASKS_DIRECTORY:-$HOME/.tasks}"
NOW=$(date +"%F %R")

if [[ ! -f $TASKS_DIRECTORY ]]
then
    mkdir -p $TASKS_DIRECTORY
fi

if [[ ! -f $TASKS_DIRECTORY/org ]]
then
    echo "default" > $TASKS_DIRECTORY/org
fi

ORGANIZATION=$(cat $TASKS_DIRECTORY/org)
export TASKS_DIRECTORY="$TASKS_DIRECTORY/$ORGANIZATION"

if [[ ! -f $TASKS_DIRECTORY/backups ]]
then
    mkdir -p $TASKS_DIRECTORY/backups
fi

usage() {
    cat <<TXT
USAGE: tasks clean

Creates a backup of the log. Then sorts and removes any malformed lines.
TXT
}

clean() {
    PARAMS=""

    while (( "$#" )); do
        case "$1" in
            -h|--help)
                usage
                exit 1
                ;;

            *)
                PARAMS="$PARAMS $1"
                shift
                ;;
        esac
    done

    ts=$(date +'%s')

    # CURRENT
    cp $TASKS_DIRECTORY/current.log $TASKS_DIRECTORY/backups/current.$ts.log
    cat $TASKS_DIRECTORY/current.log | sort -V > $TASKS_DIRECTORY/cleaning.log
    sed -i '/^$/d' $TASKS_DIRECTORY/cleaning.log
    mv $TASKS_DIRECTORY/cleaning.log $TASKS_DIRECTORY/current.log

    # ARCHIVED
    cp $TASKS_DIRECTORY/archived.log $TASKS_DIRECTORY/backups/archived.$ts.log
    cat $TASKS_DIRECTORY/archived.log | sort -V > $TASKS_DIRECTORY/cleaning.log
    sed -i '/^$/d' $TASKS_DIRECTORY/cleaning.log
    mv $TASKS_DIRECTORY/cleaning.log $TASKS_DIRECTORY/archived.log

    # DELETED
    cp $TASKS_DIRECTORY/deleted.log $TASKS_DIRECTORY/backups/deleted.$ts.log
    cat $TASKS_DIRECTORY/deleted.log | sort -V > $TASKS_DIRECTORY/cleaning.log
    sed -i '/^$/d' $TASKS_DIRECTORY/cleaning.log
    mv $TASKS_DIRECTORY/cleaning.log $TASKS_DIRECTORY/deleted.log
}

clean $*
