#!/bin/bash

set -e

LOCATION="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
DIRECTORY="${TASKS_DIRECTORY:-$HOME/.tasks}"

if [[ ! -f $DIRECTORY ]]
then
    mkdir -p $DIRECTORY
fi

echo $DIRECTORY
