#!/bin/bash

set -e

TASKS_DIRECTORY="${TASKS_DIRECTORY:-$HOME/.tasks}"
NOW=$(date +"%F %R")

if [[ ! -f $TASKS_DIRECTORY ]]
then
    mkdir -p $TASKS_DIRECTORY
fi

if [[ ! -f $TASKS_DIRECTORY/org ]]
then
    echo "default" > $TASKS_DIRECTORY/org
fi

ORGANIZATION=$(cat $TASKS_DIRECTORY/org)
export TASKS_DIRECTORY="$TASKS_DIRECTORY/$ORGANIZATION"

usage() {
    cat <<TXT
USAGE: task remove <id>

ALIASES:
    rm

ARGUMENTS:
    id  The task id
TXT
}

#
# Remove an item from the log
#
remove() {
    if [[ -z $1 ]]
    then
        usage
        exit 1
    fi

    local id=$1
    local original=$(rg -m 1 -e "$id - \\[.\\] - .*" $TASKS_DIRECTORY/current.log)

    echo "$original" >> $TASKS_DIRECTORY/deleted.log
    sed -i "/\($id - \\[.\\] - .*\)/d" $TASKS_DIRECTORY/current.log
    echo "Removed $id"
}

remove $*
