#!/bin/bash

set -e

LOCATION="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
DIRECTORY=$($LOCATION/tasks-home)/$($LOCATION/tasks-which)
NOW=$(date +"%F %R")
mkdir -p $DIRECTORY

usage() {
    cat <<TXT
USAGE: tasks add [OPTIONS]

ALIASES:
    a

OPTIONS:

    -h, --help       Output this help message
    -c, --completed  Mark this task as completed
        --id <ID>    Provide the id to assign the task. Useful if you deleted
                     a task and want to readd it later. Note, we will not try
                     to validate the uniqueness of the id. It is up to you to
                     make it uniq.
TXT
}

increment_id() {
    if [[ ! -f $DIRECTORY/taskid ]]
    then
        echo "0" > $DIRECTORY/taskid
    fi

    ID=$(cat $DIRECTORY/taskid)
    ID=$((ID + 1))
    echo "$ID" > $DIRECTORY/taskid
    echo "$ID"
}

add() {
    PARAMS=""

    while (( "$#" )); do
        case "$1" in
            -h|--help)
                usage
                exit 1
                ;;

            -c|--completed)
                shift
                COMPLETED="@completed($NOW)"
                ;;

            --id)
                if [[ -z $2 ]]
                then
                    echo "--id requires an ID to be passed"
                    exit 1
                fi

                ID=$2
                shift 2
                ;;
            *)
                PARAMS="$PARAMS $1"
                shift
                ;;
        esac
    done

    if [[ -z $PARAMS ]]
    then
        usage
        exit 1
    fi

    if [[ -z $ID ]]
    then
        ID=$(increment_id)
    fi

    if [[ -z $COMPLETED ]]
    then
        MESSAGE="$ID - [ ] - $PARAMS"
    else
        MESSAGE="$ID - [x] - $PARAMS $COMPLETED"
    fi

    echo $MESSAGE >> $DIRECTORY/current.log
    echo $MESSAGE
}

add $*
