#!/bin/bash

set -e

DIRECTORY=$(tasks-home)/$(tasks-which)
NOW=$(date +"%F %R")

usage() {
    cat <<TXT
USAGE: tasks complete <id>

ALIASES:
    c

ARGUMENTS:
    id  The task id
TXT
}

#
# Mark an item as complete
#
complete() {
    if [[ -z $1 ]]
    then
        usage
        exit 1
    fi

    ID=$1

    COMPLETED="@completed($NOW)"

    sed -i "s/$ID - \\[ \\] - \(.*\)/$ID - \\[x\\] - \\1 $COMPLETED/g" $DIRECTORY/current.log
}

complete $*
