#!/bin/bash

set -e

LOCATION="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
DIRECTORY=$($LOCATION/tasks-home)/current
mkdir -p $DIRECTORY

usage() {
    cat <<TXT
USAGE: tasks clean

Creates a backup of the log. Then sorts and removes any malformed lines.
TXT
}

clean() {
    local params=""

    while (( "$#" )); do
        case "$1" in
            -h|--help)
                usage
                exit 1
                ;;

            *)
                params="$params $1"
                shift
                ;;
        esac
    done

    local timestamp=$(date +'%s')

    if [[ ! -f $DIRECTORY/backups ]]
    then
        mkdir -p $DIRECTORY/backups
    fi

    # CURRENT
    cp $DIRECTORY/current.log $DIRECTORY/backups/current.$timestamp.log
    cat $DIRECTORY/current.log | sort -V > $DIRECTORY/cleaning.log
    sed -i '/^$/d' $DIRECTORY/cleaning.log
    mv $DIRECTORY/cleaning.log $DIRECTORY/current.log

    # ARCHIVED
    cp $DIRECTORY/archived.log $DIRECTORY/backups/archived.$timestamp.log
    cat $DIRECTORY/archived.log | sort -V > $DIRECTORY/cleaning.log
    sed -i '/^$/d' $DIRECTORY/cleaning.log
    mv $DIRECTORY/cleaning.log $DIRECTORY/archived.log

    # DELETED
    cp $DIRECTORY/deleted.log $DIRECTORY/backups/deleted.$timestamp.log
    cat $DIRECTORY/deleted.log | sort -V > $DIRECTORY/cleaning.log
    sed -i '/^$/d' $DIRECTORY/cleaning.log
    mv $DIRECTORY/cleaning.log $DIRECTORY/deleted.log
}

clean $*
