#!/bin/bash

set -e

LOCATION="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
DIRECTORY=$($LOCATION/tasks-home)
mkdir -p $DIRECTORY

if [[ -f $DIRECTORY/org ]]
then
    ORGANIZATION=$(cat $DIRECTORY/org)
else
    ORGANIZATION="default"
    echo "default" > $DIRECTORY/org
fi

usage() {
    cat <<TXT
USAGE: tasks use <name>

Changes which task list to use. Useful if you want to keep your personal
projects separate from your work projects.

ARGUMENTS:
    name  The name of the sub category of tasks
TXT
}

use() {
    params=()

    while (( "$#" )); do
        case "$1" in
            -h|--help)
                usage
                exit 1
                ;;
            *)
                params+=("$1")
                shift
                ;;
        esac
    done

    if [[ -z ${params[0]} ]]
    then
        usage
        exit 1
    fi

    changeto="${params[0]}"

    echo "Switching from $ORGANIZATION to $changeto"
    echo "$changeto" > $DIRECTORY/org

    mkdir -p $DIRECTORY/$changeto

    rm $DIRECTORY/current
    ln -s $DIRECTORY/$changeto $DIRECTORY/current
}

use $*
